ALTER TABLE orders ADD COLUMN IF NOT EXISTS carrier VARCHAR(20);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS tracking_number VARCHAR(100);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_status VARCHAR(255);